changelog:
  exclude:
    labels:
      - 'skip news'

  categories:
    - title: Bug Fixes
      labels:
        - 'bug'
        - 'news'

    - title: Enhancements
      labels:
        - 'feature-request'
        - 'news'

    - title: Code Health
      labels:
        - 'debt'
        - 'news'
